services:
  db:
    image: library/postgres:13.3-alpine
    container_name: "search_test_postgres"
    ports: 
      - "54321:5432"
    volumes:
      - postgres_data1:/var/lib/postgresql/data
    environment: 
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
volumes: 
  postgres_data1:
    name: search_test_data1